try :
    a = 1200 /0

except Exception as erro:
    print('Aconteceu algum erro:', erro)